### ISSUE TITLE
IEMOCAP audio feature dimention is 1582 which should be 100

### ISSUE THREAD

**Issue by sailist** [hujingwen6666/MMGCN#3]
When it comes to audio feature, you said the acoustic raw features are extracted using the OpenSmile toolkit with IS10 configuration, which should be 100 dimention. This configuration was also used in paper "COGMEN COntextualized GNN based Multimodal Emotion recognitioN".

Your code runs well, but when I print the audio feature shape, I got 1582 dimention instead of 100.
```
torch.Size([50, 1582])
torch.Size([44, 1582])
torch.Size([40, 1582])
torch.Size([27, 1582])
torch.Size([38, 1582])
torch.Size([26, 1582])
torch.Size([47, 1582])
torch.Size([60, 1582])
```

May I ask how do you get the acoustic feature?

**Comment by sailist** [comment]
I got it, it should be 1582, not 100.

**Comment by Coding511** [comment]
@sailist In Iemocap only scripted version of the dataset is used. Is it correct? Plz help

**Comment by sailist** [comment]
What is the meaning of 'scripted version' and 'correct'?

**Comment by Coding511** [comment]
There are two versions of this datasets , improvised and scripted.
Did they used only scripted as stated in paper, But there features are indicating they have used all 5531 utterances.
Can we talk on email if possible.

**Comment by sailist** [comment]
Where can you find the improvised and scripted feature files? I still can't understand your intention. My suggestion is to use COGMEN's IEMOCAP feature file to train a IEMOCAP model and use MMGCN's MELD feature file to train a MELD modal. You can easily find them from each repository.

Welcome to email me if you want, but I'd better like discussing in github.

**Comment by Coding511** [comment]
Thanks. All I am saying IEMOCAP has two versions in dataset total 5531 files using four emotions only, including improvised and scripted utterances. Few people use only improvised or only scripted and of course few used combination of both that is 5531 files.
I think you did not use this dataset from scratch but these readymade features only.

**Comment by Coding511** [comment]
Also through email I can show you my code snippets where I am getting better results on IEMOCAP.
But I am not able to execute this MMGCN code, it gt stuck at 
NotImplement Error.
